name: 'Setup Nix and Cachix'
description: 'Install Nix and configure the Chiri Cachix cache.'

inputs:
  cache-name:
    description: 'Cachix cache name.'
    required: false
    default: 'chiri'
  auth-token:
    description: 'Cachix auth token.'
    required: false
    default: ''
  skip-push:
    description: 'Whether Cachix should skip pushing new paths.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25

    - name: Set up Cachix
      uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: ${{ inputs.cache-name }}
        authToken: ${{ inputs.auth-token }}
        skipPush: ${{ inputs.skip-push }}
